[mypy]
python_version = 3.11
warn_unused_configs = True
warn_unused_ignores = True
warn_return_any = True
plugins = pydantic.mypy

[mypy-app.*]
disallow_untyped_defs = True

[mypy-tests.*]
ignore_missing_imports = True
disallow_untyped_defs = False

[mypy-app.agent.*]
ignore_missing_imports = True

[mypy-app.agent.graph]
allow_redefinition = True

[mypy-debugpy]
ignore_missing_imports = True
