[mypy]
python_version = 3.11
warn_unused_configs = True
warn_unused_ignores = False
warn_return_any = False
ignore_missing_imports = True
plugins = pydantic.mypy

[mypy-app.*]
disallow_untyped_defs = False
disable_error_code = arg-type,assignment,attr-defined,call-arg,call-overload,dict-item,import-not-found,import-untyped,index,list-item,misc,no-any-return,no-redef,operator,override,return-value,typeddict-item,typeddict-unknown-key,union-attr,unused-ignore,valid-type,var-annotated

[mypy-tests.*]
ignore_missing_imports = True
disallow_untyped_defs = False

[mypy-app.agent.*]
ignore_missing_imports = True

[mypy-app.agent.graph]
allow_redefinition = True

[mypy-debugpy]
ignore_missing_imports = True
