line-length = 100
target-version = "py311"

lint.select = ["E", "F", "W", "I", "UP", "B"]
lint.ignore = ["E203", "B008"]

format.quote-style = "double"
format.indent-style = "space"
format.skip-magic-trailing-comma = false
