"""The private delegated local-operator principal record (MVR-03).

`docs/MULTI_VAULT_RUNTIME/VERSION_ACTIVE_CONTEXT_SELECTION.md` requires MVR-03 to own the
*missing producer* for the principal the active-context seam resolves. Before this slice the
runtime had credentials (`app/auth.py`) but no principal: an API key is a credential, and
`appInstallId` is instance identity, and neither is a principal.

This module supplies exactly that missing producer and nothing more:

- one opaque, server-minted `local_operator_role_id` denoting an **instance-scoped delegated
  operator role**, not the human's global identity,
- a private, versioned, mode-`0600` record under the MVR-01 instance-state boundary, with its
  own schema, monotonic revision, migration provenance, and a lock / atomic-write / fsync
  path modelled on `VaultRegistryStore`,
- server-derived subject binding: `trusted_loopback`, `trusted_companion_proxy`, and
  `api_key_credential` (by non-reversible fingerprint -- never the raw key),
- fail-closed preflight for ambiguous, missing, partial, or unsafe state, each naming an
  explicit provisioning action.

The role id is generated by CSPRNG. It is never derived from `appInstallId`, from the
credential value, from a path, or from a correlation id -- `test_instance_identity_never_
substitutes_for_principal_context` pins that.

Ordering rule the contract makes non-negotiable: the `minimum_runtime_principal` floor is
recorded **before** the first durable role write. `bootstrap()` refuses to write without
proof the floor already landed, so a crash before the floor leaves old auth state
authoritative and this migration untouched.
"""

from __future__ import annotations

import fcntl
import hashlib
import hmac
import json
import os
import secrets
import stat
import tempfile
import time
from collections.abc import Iterator, Mapping, Sequence
from contextlib import contextmanager
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any, Literal

from app.instance._storage_boundary import (
    CapabilityNotReadyError,
    RegistryError,
    _require_storage_mutation_capability,
)
from app.vault.active_context_v1 import AuthSubject, PrincipalContext, PrincipalKind

LOCAL_OPERATOR_PRINCIPAL_SCHEMA = "agentic-pkm.local-operator-principal.v1"

#: Recorded in `runtimeFloors` alongside MVR-01's `minimumRuntimeSchema`. The MVR-01 scalar
#: rollback preflight refuses a credential-only image while this floor exists.
MINIMUM_RUNTIME_PRINCIPAL_KEY = "minimumRuntimePrincipal"
MINIMUM_RUNTIME_PRINCIPAL = "mvr-03"

#: The record file name, a sibling of `vault-registry.md` inside the private 0700
#: instance-state directory (native installs get the same file in private app-data).
PRINCIPAL_RECORD_FILENAME = "local-operator-principal.json"

#: The stopped-window export is its own versioned artifact, checked before its contents are
#: trusted for lineage.
_ROLL_FORWARD_EXPORT_SCHEMA = f"{LOCAL_OPERATOR_PRINCIPAL_SCHEMA}.roll-forward-export"

SUBJECT_LOOPBACK: AuthSubject = "trusted_loopback"
SUBJECT_COMPANION_PROXY: AuthSubject = "trusted_companion_proxy"
SUBJECT_API_KEY: AuthSubject = "api_key_credential"

ALL_SUBJECTS: tuple[AuthSubject, ...] = (
    SUBJECT_LOOPBACK,
    SUBJECT_COMPANION_PROXY,
    SUBJECT_API_KEY,
)

PROVENANCE_EXISTING_CREDENTIAL = "existing_single_user_credential_migration"
PROVENANCE_FRESH_BOOTSTRAP = "fresh_instance_bootstrap"
PROVENANCE_ROLL_FORWARD = "roll_forward_reconciled"
PROVENANCE_ZERO_KEY_LOOPBACK = "zero_credential_loopback_bootstrap"

MIGRATION_PROVENANCES: frozenset[str] = frozenset(
    {
        PROVENANCE_EXISTING_CREDENTIAL,
        PROVENANCE_FRESH_BOOTSTRAP,
        PROVENANCE_ROLL_FORWARD,
        PROVENANCE_ZERO_KEY_LOOPBACK,
    }
)

RoleKind = Literal["human", "agent"]


class PrincipalPreflightError(RegistryError):
    """Fail-closed principal state, carrying the explicit provisioning action to take."""

    def __init__(self, message: str, *, provisioning_action: str) -> None:
        super().__init__(f"{message}; provisioning action: {provisioning_action}")
        self.provisioning_action = provisioning_action


class PrincipalFloorNotRecordedError(CapabilityNotReadyError):
    """A durable role write was attempted before the minimum-runtime principal floor."""


#: Salted, memory-hard KDF parameters for the credential fingerprint. A plain SHA-256 of a
#: credential is cheap to brute-force offline, which matters here: the fingerprint is stored
#: at rest, and while the record is mode `0600` the whole point of a fingerprint is that
#: losing the file must not lose the credential. scrypt at these parameters is the stdlib's
#: memory-hard option and costs ~100ms, which is why derivation is memoized below.
_SCRYPT_N = 2**14
_SCRYPT_R = 8
_SCRYPT_P = 1
_SCRYPT_DKLEN = 32
_FINGERPRINT_PREFIX = "scrypt.v1"


def new_credential_salt() -> str:
    """A fresh per-record CSPRNG salt, so two instances never share a fingerprint space."""

    return secrets.token_hex(16)


@lru_cache(maxsize=32)
def _derive(raw_credential: str, salt: str) -> str:
    return hashlib.scrypt(
        f"mvr03.credential-fingerprint.v1|{raw_credential}".encode(),
        salt=bytes.fromhex(salt),
        n=_SCRYPT_N,
        r=_SCRYPT_R,
        p=_SCRYPT_P,
        dklen=_SCRYPT_DKLEN,
    ).hex()


def fingerprint_credential(raw_credential: str, salt: str) -> str:
    """Salted, memory-hard fingerprint of a configured #2223 credential.

    The raw key never reaches durable state, a log, a receipt, or a cache key. Only this
    value is stored, and it is domain-separated so it cannot collide with any other digest
    in the system.

    Derivation is memoized because the configured credential and the record salt are both
    process-stable, so the ~100ms scrypt cost is paid once per process rather than per
    request. The cache holds no more than what `app.settings.settings.api_key` already holds
    in memory.
    """

    if not raw_credential:
        raise ValueError("cannot fingerprint an empty credential")
    if not salt:
        raise ValueError("a credential fingerprint requires a salt")
    return f"{_FINGERPRINT_PREFIX}${salt}${_derive(raw_credential, salt)}"


def verify_credential(stored_fingerprint: str | None, raw_credential: str | None) -> bool:
    """Constant-time check of a presented credential against the stored fingerprint."""

    if not stored_fingerprint or not raw_credential:
        return False
    parts = stored_fingerprint.split("$")
    if len(parts) != 3 or parts[0] != _FINGERPRINT_PREFIX:
        return False
    _, salt, _digest = parts
    try:
        candidate = fingerprint_credential(raw_credential, salt)
    except ValueError:
        return False
    return hmac.compare_digest(candidate, stored_fingerprint)


def fingerprint_salt(stored_fingerprint: str | None) -> str | None:
    """The salt a stored fingerprint was derived under, so a re-derivation can match it."""

    if not stored_fingerprint:
        return None
    parts = stored_fingerprint.split("$")
    return parts[1] if len(parts) == 3 and parts[0] == _FINGERPRINT_PREFIX else None


@dataclass(frozen=True)
class AdditionalRole:
    """An explicitly added human or agent role.

    It receives a **distinct** principal id. Adding a role never merges into, aliases, or
    widens the delegated operator role.
    """

    role_id: str
    kind: RoleKind
    label: str
    created_at: float

    def as_payload(self) -> dict[str, Any]:
        return {
            "role_id": self.role_id,
            "kind": self.kind,
            "label": self.label,
            "created_at": self.created_at,
        }


@dataclass(frozen=True)
class LocalOperatorPrincipalRecord:
    """The durable delegated-role record."""

    schema: str
    revision: int
    local_operator_role_id: str
    subjects: tuple[AuthSubject, ...]
    credential_fingerprint: str | None
    migration_provenance: str
    created_at: float
    updated_at: float
    additional_roles: tuple[AdditionalRole, ...] = ()

    def as_payload(self) -> dict[str, Any]:
        return {
            "schema": self.schema,
            "revision": self.revision,
            "local_operator_role_id": self.local_operator_role_id,
            "subjects": sorted(self.subjects),
            "credential_fingerprint": self.credential_fingerprint,
            "migration_provenance": self.migration_provenance,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "additional_roles": [role.as_payload() for role in self.additional_roles],
        }

    def principal_for(self, subject: AuthSubject) -> PrincipalContext:
        if subject not in self.subjects:
            raise PrincipalPreflightError(
                f"subject {subject} is not bound to the local delegated role",
                provisioning_action="run principal bootstrap for this deployment posture",
            )
        return PrincipalContext(
            principal_id=self.local_operator_role_id,
            principal_kind="delegated_operator_role",
            subject=subject,
        )

    def additional_principal(self, role_id: str, subject: AuthSubject) -> PrincipalContext:
        for role in self.additional_roles:
            if role.role_id == role_id:
                kind: PrincipalKind = "human" if role.kind == "human" else "delegated_operator_role"
                return PrincipalContext(
                    principal_id=role.role_id,
                    principal_kind=kind,
                    subject=subject,
                )
        raise PrincipalPreflightError(
            "unknown principal role",
            provisioning_action="add the role through the governed add-role command",
        )


def _now() -> float:
    return time.time()


def _mint_role_id() -> str:
    """CSPRNG-minted opaque role id.

    Derived from nothing: not the credential, not `appInstallId`, not a path.
    """

    return f"lor_{secrets.token_hex(16)}"


class LocalOperatorPrincipalStore:
    """Private, versioned, lock-protected store for the delegated-role record.

    Mutating methods take the sealed `app.instance._storage_boundary` capability, matching
    every other durable instance-state writer. Production callers reach them through
    `app.instance.runtime.open_local_operator_principal_store`.
    """

    def __init__(self, path: Path) -> None:
        self.path = Path(path)
        self.lock_path = self.path.with_suffix(self.path.suffix + ".lock")
        self.export_path = self.path.with_suffix(self.path.suffix + ".roll-forward-export")

    # -- private io ---------------------------------------------------------

    @contextmanager
    def _locked(self) -> Iterator[None]:
        self._ensure_private_directory(self.path.parent)
        descriptor = os.open(
            self.lock_path,
            os.O_RDWR | os.O_CREAT | getattr(os, "O_NOFOLLOW", 0),
            0o600,
        )
        try:
            os.fchmod(descriptor, 0o600)
        except BaseException:
            os.close(descriptor)
            raise
        with os.fdopen(descriptor, "a+b", closefd=True) as handle:
            fcntl.flock(handle.fileno(), fcntl.LOCK_EX)
            try:
                yield
            finally:
                fcntl.flock(handle.fileno(), fcntl.LOCK_UN)

    @staticmethod
    def _ensure_private_directory(directory: Path) -> None:
        directory.mkdir(parents=True, exist_ok=True, mode=0o700)
        try:
            metadata = directory.lstat()
        except OSError as error:
            raise PrincipalPreflightError(
                "principal state directory is unreadable",
                provisioning_action="restore the instance-state mount and re-run preflight",
            ) from error
        if not stat.S_ISDIR(metadata.st_mode):
            raise PrincipalPreflightError(
                "principal state parent is not a directory",
                provisioning_action="remove the conflicting path and re-run preflight",
            )
        if metadata.st_uid != os.geteuid():
            raise PrincipalPreflightError(
                "principal state directory is not owned by the runtime user",
                provisioning_action="chown the instance-state directory to the runtime user",
            )
        if metadata.st_mode & 0o777 != 0o700:
            os.chmod(directory, 0o700)

    @staticmethod
    def _atomic_private_write(path: Path, payload: bytes) -> None:
        descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
        temporary = Path(temporary_name)
        try:
            os.fchmod(descriptor, 0o600)
            with os.fdopen(descriptor, "wb", closefd=True) as handle:
                handle.write(payload)
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(temporary, path)
            os.chmod(path, 0o600)
            directory = os.open(path.parent, os.O_RDONLY | getattr(os, "O_DIRECTORY", 0))
            try:
                os.fsync(directory)
            finally:
                os.close(directory)
        except BaseException:
            temporary.unlink(missing_ok=True)
            raise

    def _read_private_json(self, path: Path) -> dict[str, Any]:
        # Open first, then validate the *descriptor* and read from it. Validating a path with
        # `lstat` and then re-resolving it with `read_text` is a TOCTOU window; `O_NOFOLLOW`
        # plus `fstat` closes it, matching the lock path's posture.
        try:
            descriptor = os.open(path, os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0))
        except OSError as error:
            raise PrincipalPreflightError(
                "principal record is unreadable or is a symlink",
                provisioning_action="remove the unsafe path and re-run principal bootstrap",
            ) from error
        try:
            metadata = os.fstat(descriptor)
            if not stat.S_ISREG(metadata.st_mode):
                raise PrincipalPreflightError(
                    "principal record is not a regular file",
                    provisioning_action="remove the unsafe path and re-run principal bootstrap",
                )
            if metadata.st_uid != os.geteuid():
                raise PrincipalPreflightError(
                    "principal record ownership is unsafe",
                    provisioning_action="chown the principal record to the runtime user",
                )
            if metadata.st_mode & 0o777 != 0o600:
                raise PrincipalPreflightError(
                    f"principal record mode is unsafe: {oct(metadata.st_mode & 0o777)}",
                    provisioning_action="chmod 0600 the principal record",
                )
            raw = os.read(descriptor, metadata.st_size)
        finally:
            os.close(descriptor)
        try:
            payload = json.loads(raw.decode("utf-8"))
        except (OSError, ValueError) as error:
            raise PrincipalPreflightError(
                "principal record is unreadable or malformed",
                provisioning_action="restore the principal record from backup, then re-run preflight",
            ) from error
        if not isinstance(payload, dict):
            raise PrincipalPreflightError(
                "principal record is not an object",
                provisioning_action="restore the principal record from backup, then re-run preflight",
            )
        return payload

    def _consume_export(self) -> None:
        """Unlink the export and fsync its parent, so the deletion survives power loss.

        Without the directory fsync a consumed export can reappear after a crash while the
        principal revision has already advanced; the next roll-forward would then reject its
        now-stale fork and block recovery.
        """

        self.export_path.unlink(missing_ok=True)
        directory = os.open(
            self.export_path.parent, os.O_RDONLY | getattr(os, "O_DIRECTORY", 0)
        )
        try:
            os.fsync(directory)
        finally:
            os.close(directory)

    @staticmethod
    def _serialize(payload: Mapping[str, Any]) -> bytes:
        return json.dumps(dict(payload), sort_keys=True, separators=(",", ":")).encode() + b"\n"

    # -- read ---------------------------------------------------------------

    def exists(self) -> bool:
        return self.path.exists()

    def load(self) -> LocalOperatorPrincipalRecord | None:
        """Return the record, or None when no record has been written yet.

        A *partial* record is never returned as None: it raises, because silently treating
        a half-written record as "no principal yet" would re-run bootstrap over live state.
        """

        if not self.path.exists():
            return None
        return _parse_record(self._read_private_json(self.path))

    def require(self) -> LocalOperatorPrincipalRecord:
        record = self.load()
        if record is None:
            raise PrincipalPreflightError(
                "no delegated operator role is provisioned",
                provisioning_action=(
                    "run `python -m app.instance.runtime principal-bootstrap "
                    "--registry-path <path>`"
                ),
            )
        return record

    # -- write --------------------------------------------------------------

    def bootstrap(
        self,
        *,
        credential: str | None,
        subjects: Sequence[AuthSubject],
        migration_provenance: str,
        floor_recorded: bool,
        _capability: Any = None,
    ) -> LocalOperatorPrincipalRecord:
        """Write the first durable delegated-role record.

        Idempotent: a second call with the same inputs returns the existing record rather
        than minting a second role id, so channel init, native init, and test fixtures can
        all call it without racing a new identity into existence.
        """

        _require_storage_mutation_capability(_capability)
        if not floor_recorded:
            raise PrincipalFloorNotRecordedError(
                "the minimum_runtime_principal floor must be recorded before the first "
                "durable delegated-role write"
            )
        credential_fingerprint = (
            fingerprint_credential(credential, new_credential_salt()) if credential else None
        )
        if migration_provenance not in MIGRATION_PROVENANCES:
            raise PrincipalPreflightError(
                f"unknown migration provenance {migration_provenance!r}",
                provisioning_action="use a declared MVR-03 migration provenance",
            )
        normalized = _normalize_subjects(subjects)
        if SUBJECT_API_KEY in normalized and not credential_fingerprint:
            raise PrincipalPreflightError(
                "the api_key_credential subject requires a credential fingerprint",
                provisioning_action="provision a #2223 API key, then re-run principal bootstrap",
            )
        with self._locked():
            existing = self.load()
            if existing is not None:
                if (
                    existing.credential_fingerprint == credential_fingerprint
                    and existing.subjects == normalized
                    and existing.migration_provenance == migration_provenance
                ):
                    return existing
                raise PrincipalPreflightError(
                    "a delegated operator role already exists with different auth state",
                    provisioning_action=(
                        "use the governed rotate-credential or add-subject command instead of "
                        "re-bootstrapping"
                    ),
                )
            now = _now()
            record = LocalOperatorPrincipalRecord(
                schema=LOCAL_OPERATOR_PRINCIPAL_SCHEMA,
                revision=1,
                local_operator_role_id=_mint_role_id(),
                subjects=normalized,
                credential_fingerprint=credential_fingerprint,
                migration_provenance=migration_provenance,
                created_at=now,
                updated_at=now,
            )
            self._atomic_private_write(self.path, self._serialize(record.as_payload()))
            return record

    def rotate_credential(
        self,
        *,
        credential: str | None,
        _capability: Any = None,
    ) -> LocalOperatorPrincipalRecord:
        """Rebind a rotated credential to the **same** role id.

        Rotation never mints a new principal, and it never disables the already-supported
        loopback / proxy subjects: only an explicit governed posture change may revoke one.
        """

        _require_storage_mutation_capability(_capability)
        with self._locked():
            current = self.require()
            if not credential and SUBJECT_API_KEY in current.subjects:
                # An empty rotation would keep `api_key_credential` bound with no
                # fingerprint, so every admitted key would then fail verification and the
                # instance could be left with no usable principal -- routing around
                # `revoke_subject`'s last-subject safeguard. Dropping a credential is a
                # governed posture change, not a rotation.
                raise PrincipalPreflightError(
                    "an empty credential is not a rotation",
                    provisioning_action=(
                        "supply the new credential on stdin, or use "
                        "`principal-revoke-subject --subject api_key_credential` to drop it"
                    ),
                )
            # A rotation keeps the record's salt space fresh: a new credential gets a new
            # salt, so the stored value changes even if the operator rotates back.
            credential_fingerprint = (
                fingerprint_credential(credential, new_credential_salt())
                if credential
                else None
            )
            subjects = set(current.subjects)
            if credential_fingerprint:
                subjects.add(SUBJECT_API_KEY)
            record = LocalOperatorPrincipalRecord(
                schema=current.schema,
                revision=current.revision + 1,
                local_operator_role_id=current.local_operator_role_id,
                subjects=_normalize_subjects(tuple(subjects)),
                credential_fingerprint=credential_fingerprint,
                migration_provenance=current.migration_provenance,
                created_at=current.created_at,
                updated_at=_now(),
                additional_roles=current.additional_roles,
            )
            self._atomic_private_write(self.path, self._serialize(record.as_payload()))
            return record

    def revoke_subject(
        self,
        subject: AuthSubject,
        *,
        _capability: Any = None,
    ) -> LocalOperatorPrincipalRecord:
        """Explicit governed posture change: atomically drop one subject."""

        _require_storage_mutation_capability(_capability)
        with self._locked():
            current = self.require()
            if subject not in current.subjects:
                # Reporting success for a subject that was never bound would be a false
                # governed receipt, and the revision bump would silently invalidate any
                # roll-forward export already taken at the current revision.
                raise PrincipalPreflightError(
                    f"subject {subject} is not bound to the local delegated role",
                    provisioning_action="revoke only a currently bound subject",
                )
            remaining = tuple(item for item in current.subjects if item != subject)
            if not remaining:
                raise PrincipalPreflightError(
                    "revoking the last subject would leave the instance with no principal",
                    provisioning_action="provision another subject before revoking this one",
                )
            record = LocalOperatorPrincipalRecord(
                schema=current.schema,
                revision=current.revision + 1,
                local_operator_role_id=current.local_operator_role_id,
                subjects=remaining,
                credential_fingerprint=(
                    None if subject == SUBJECT_API_KEY else current.credential_fingerprint
                ),
                migration_provenance=current.migration_provenance,
                created_at=current.created_at,
                updated_at=_now(),
                additional_roles=current.additional_roles,
            )
            self._atomic_private_write(self.path, self._serialize(record.as_payload()))
            return record

    def add_role(
        self,
        *,
        kind: RoleKind,
        label: str,
        _capability: Any = None,
    ) -> tuple[LocalOperatorPrincipalRecord, AdditionalRole]:
        """Add an explicitly declared human or agent role with a distinct principal id."""

        _require_storage_mutation_capability(_capability)
        with self._locked():
            current = self.require()
            role = AdditionalRole(
                role_id=_mint_role_id(),
                kind=kind,
                label=label,
                created_at=_now(),
            )
            record = LocalOperatorPrincipalRecord(
                schema=current.schema,
                revision=current.revision + 1,
                local_operator_role_id=current.local_operator_role_id,
                subjects=current.subjects,
                credential_fingerprint=current.credential_fingerprint,
                migration_provenance=current.migration_provenance,
                created_at=current.created_at,
                updated_at=_now(),
                additional_roles=current.additional_roles + (role,),
            )
            self._atomic_private_write(self.path, self._serialize(record.as_payload()))
            return record, role

    # -- roll-forward lineage ------------------------------------------------

    def export_final_auth_state(
        self,
        *,
        credential: str | None,
        fork_revision: int,
        _capability: Any = None,
    ) -> dict[str, Any]:
        """Export the prior image's final credential/auth revision under the lock.

        Compatible roll-forward reads this export, verifies its recorded fork, and
        reconciles an unambiguous credential rotation into the same role id.
        """

        _require_storage_mutation_capability(_capability)
        with self._locked():
            # Derived under the CURRENT record's salt so the reconcile below can compare by
            # equality: an export of the same credential is byte-identical and takes the
            # no-op branch, while a genuinely rotated credential differs.
            existing = self.load()
            salt = fingerprint_salt(
                existing.credential_fingerprint if existing is not None else None
            )
            credential_fingerprint = (
                fingerprint_credential(credential, salt or new_credential_salt())
                if credential
                else None
            )
            payload = {
                "schema": _ROLL_FORWARD_EXPORT_SCHEMA,
                "fork_revision": fork_revision,
                "credential_fingerprint": credential_fingerprint,
                "exported_at": _now(),
            }
            self._atomic_private_write(self.export_path, self._serialize(payload))
            return payload

    def reconcile_roll_forward(
        self,
        *,
        _capability: Any = None,
    ) -> LocalOperatorPrincipalRecord:
        """Reconcile the exported prior-image auth state into the existing role.

        Fail-closed cases, none of which overwrite either lineage:

        - a missing export,
        - an export whose recorded fork does not match this record's revision (divergent),
        - an export with no credential fingerprint while the record still has one, or the
          reverse (ambiguous -- this cannot be told apart from a revocation).
        """

        _require_storage_mutation_capability(_capability)
        with self._locked():
            current = self.require()
            if not self.export_path.exists():
                raise PrincipalPreflightError(
                    "compatible roll-forward requires the prior image's final auth export",
                    provisioning_action="re-run the stopped-window export before roll-forward",
                )
            export = self._read_private_json(self.export_path)
            if export.get("schema") != _ROLL_FORWARD_EXPORT_SCHEMA:
                # A mixed-version or corrupted export must not be interpreted as v1. Without
                # this, any private JSON object carrying a matching `fork_revision` and a
                # string fingerprint could overwrite the principal record with the wrong
                # credential instead of failing closed.
                raise PrincipalPreflightError(
                    f"unknown roll-forward export schema {export.get('schema')!r}",
                    provisioning_action=(
                        "re-run the stopped-window export with a compatible image; nothing "
                        "was overwritten"
                    ),
                )
            fork_revision = export.get("fork_revision")
            # `!=`, not `>`. A fork *below* the current revision is a stale export, and
            # accepting it would let a leftover file replay an old credential over a later
            # governed rotation. The export is also consumed on success (below), so a
            # successful reconcile cannot be replayed at all.
            if not isinstance(fork_revision, int) or fork_revision != current.revision:
                raise PrincipalPreflightError(
                    "roll-forward export fork does not match the current principal lineage "
                    f"(export fork {fork_revision!r}, record revision {current.revision})",
                    provisioning_action="resolve the divergent auth lineage manually; nothing was overwritten",
                )
            exported_fingerprint = export.get("credential_fingerprint")
            if exported_fingerprint is not None and (
                not isinstance(exported_fingerprint, str)
                or fingerprint_salt(exported_fingerprint) is None
            ):
                raise PrincipalPreflightError(
                    "roll-forward export credential state is ambiguous",
                    provisioning_action="resolve the ambiguous auth lineage manually; nothing was overwritten",
                )
            if exported_fingerprint == current.credential_fingerprint:
                # Nothing to reconcile. Consume the export so it cannot be replayed later
                # against a rotated record.
                self._consume_export()
                return current
            if exported_fingerprint is None or current.credential_fingerprint is None:
                raise PrincipalPreflightError(
                    "roll-forward cannot tell a credential rotation from a revocation",
                    provisioning_action="perform an explicit governed posture change instead",
                )
            subjects = _normalize_subjects(tuple(set(current.subjects) | {SUBJECT_API_KEY}))
            record = LocalOperatorPrincipalRecord(
                schema=current.schema,
                revision=current.revision + 1,
                local_operator_role_id=current.local_operator_role_id,
                subjects=subjects,
                credential_fingerprint=exported_fingerprint,
                migration_provenance=PROVENANCE_ROLL_FORWARD,
                created_at=current.created_at,
                updated_at=_now(),
                additional_roles=current.additional_roles,
            )
            self._atomic_private_write(self.path, self._serialize(record.as_payload()))
            self._consume_export()
            return record


def _normalize_subjects(subjects: Sequence[AuthSubject]) -> tuple[AuthSubject, ...]:
    unique = set(subjects)
    unknown = unique - set(ALL_SUBJECTS)
    if unknown:
        raise PrincipalPreflightError(
            f"unknown authentication subject(s): {sorted(unknown)}",
            provisioning_action="bind only server-derived subjects",
        )
    if not unique:
        raise PrincipalPreflightError(
            "a delegated role requires at least one server-derived subject",
            provisioning_action="run principal bootstrap with the deployment's real posture",
        )
    return tuple(subject for subject in ALL_SUBJECTS if subject in unique)


def _parse_record(payload: Mapping[str, Any]) -> LocalOperatorPrincipalRecord:
    schema = payload.get("schema")
    if schema != LOCAL_OPERATOR_PRINCIPAL_SCHEMA:
        raise PrincipalPreflightError(
            f"unknown principal record schema {schema!r}",
            provisioning_action="upgrade to an image that understands this principal schema",
        )
    required = (
        "revision",
        "local_operator_role_id",
        "subjects",
        "migration_provenance",
        "created_at",
        "updated_at",
    )
    missing = [key for key in required if key not in payload]
    if missing:
        raise PrincipalPreflightError(
            f"partial principal record; missing {missing}",
            provisioning_action="restore the principal record from backup, then re-run preflight",
        )
    revision = payload["revision"]
    role_id = payload["local_operator_role_id"]
    if not isinstance(revision, int) or revision < 1:
        raise PrincipalPreflightError(
            "principal record revision is invalid",
            provisioning_action="restore the principal record from backup, then re-run preflight",
        )
    if not isinstance(role_id, str) or not role_id:
        raise PrincipalPreflightError(
            "principal record role id is invalid",
            provisioning_action="restore the principal record from backup, then re-run preflight",
        )
    raw_subjects = payload["subjects"]
    if not isinstance(raw_subjects, list):
        raise PrincipalPreflightError(
            "principal record subjects are invalid",
            provisioning_action="restore the principal record from backup, then re-run preflight",
        )
    fingerprint = payload.get("credential_fingerprint")
    if fingerprint is not None and not isinstance(fingerprint, str):
        raise PrincipalPreflightError(
            "principal record credential fingerprint is invalid",
            provisioning_action="restore the principal record from backup, then re-run preflight",
        )
    roles: list[AdditionalRole] = []
    for raw_role in payload.get("additional_roles") or []:
        if not isinstance(raw_role, dict):
            raise PrincipalPreflightError(
                "principal record additional role is invalid",
                provisioning_action="restore the principal record from backup, then re-run preflight",
            )
        roles.append(
            AdditionalRole(
                role_id=str(raw_role["role_id"]),
                kind="human" if raw_role.get("kind") == "human" else "agent",
                label=str(raw_role.get("label") or ""),
                created_at=float(raw_role.get("created_at") or 0.0),
            )
        )
    return LocalOperatorPrincipalRecord(
        schema=LOCAL_OPERATOR_PRINCIPAL_SCHEMA,
        revision=revision,
        local_operator_role_id=role_id,
        subjects=_normalize_subjects(tuple(raw_subjects)),
        credential_fingerprint=fingerprint,
        migration_provenance=str(payload["migration_provenance"]),
        created_at=float(payload["created_at"]),
        updated_at=float(payload["updated_at"]),
        additional_roles=tuple(roles),
    )


@dataclass(frozen=True)
class AuthPosture:
    """The deployment's real, server-derived authentication posture.

    Every field is derived from server configuration and the effective listener, never from
    a client header. `configured_credentials` is a *count* so an ambiguous multi-credential
    posture is representable and rejectable.
    """

    configured_credentials: int
    #: The configured credential itself, in memory only. It is derived into a salted,
    #: memory-hard fingerprint at write time and never stored raw. Holding it here is not a
    #: new exposure: it is the same value `app.settings.settings.api_key` already holds.
    credential: str | None
    loopback_listener_proven: bool
    companion_proxy_configured: bool

    def subjects(self) -> tuple[AuthSubject, ...]:
        subjects: list[AuthSubject] = []
        if self.loopback_listener_proven:
            subjects.append(SUBJECT_LOOPBACK)
        if self.companion_proxy_configured:
            subjects.append(SUBJECT_COMPANION_PROXY)
        if self.credential:
            subjects.append(SUBJECT_API_KEY)
        return tuple(subjects)

    def migration_provenance(self, *, existing_install: bool) -> str:
        if self.credential:
            return PROVENANCE_EXISTING_CREDENTIAL if existing_install else PROVENANCE_FRESH_BOOTSTRAP
        return PROVENANCE_ZERO_KEY_LOOPBACK


def preflight_auth_posture(posture: AuthPosture) -> tuple[AuthSubject, ...]:
    """Validate the posture and return the subjects to bind, or fail with an action.

    The rejected postures are exactly the ones the contract names: multiple ambiguous
    credentials, and any other zero-credential non-loopback posture.
    """

    if posture.configured_credentials > 1:
        raise PrincipalPreflightError(
            f"{posture.configured_credentials} ambiguous credentials are configured",
            provisioning_action=(
                "reduce the deployment to one #2223 credential, then re-run principal bootstrap"
            ),
        )
    subjects = posture.subjects()
    if not subjects:
        raise PrincipalPreflightError(
            "a zero-credential non-loopback deployment has no server-derivable principal",
            provisioning_action=(
                "complete governed credential provisioning (set API_KEY) or expose the "
                "listener on loopback / a configured Companion proxy"
            ),
        )
    return subjects


__all__ = [
    "ALL_SUBJECTS",
    "LOCAL_OPERATOR_PRINCIPAL_SCHEMA",
    "MIGRATION_PROVENANCES",
    "MINIMUM_RUNTIME_PRINCIPAL",
    "MINIMUM_RUNTIME_PRINCIPAL_KEY",
    "PRINCIPAL_RECORD_FILENAME",
    "PROVENANCE_EXISTING_CREDENTIAL",
    "PROVENANCE_FRESH_BOOTSTRAP",
    "PROVENANCE_ROLL_FORWARD",
    "PROVENANCE_ZERO_KEY_LOOPBACK",
    "SUBJECT_API_KEY",
    "SUBJECT_COMPANION_PROXY",
    "SUBJECT_LOOPBACK",
    "AdditionalRole",
    "AuthPosture",
    "LocalOperatorPrincipalRecord",
    "LocalOperatorPrincipalStore",
    "PrincipalFloorNotRecordedError",
    "PrincipalPreflightError",
    "fingerprint_credential",
    "fingerprint_salt",
    "new_credential_salt",
    "preflight_auth_posture",
    "verify_credential",
]
