from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field

from app.events.panel import NoteRef, PanelIntentAction


class PanelActionIntent(BaseModel):
    """Structured intent generated by PanelAgent to describe which actions to run for a note."""

    note: NoteRef
    instruction: str = ""
    actions: List[str] = Field(default_factory=list)
    source: str = "panel_agent"
    resolved_actions: List[PanelIntentAction] = Field(default_factory=list)


__all__ = ["PanelActionIntent"]
