"""Bounded rebuildability contracts for Product projections."""

from .product_total_loss import (
    PRODUCT_REPLAY_RECIPE_VERSION,
    ProductReadiness,
    ProductReplayRefusal,
    ProductReplayTuple,
    canonical_product_body_text,
    canonical_product_source_text,
    evaluate_product_store_readiness,
    parse_bounded_frontmatter,
    parse_markdown_text,
    product_replay_provenance,
)
from .product_projection_rebuild import (
    DbOutboxProjectionQueue,
    DurableProjectionWork,
    ProjectionRelation,
    ProjectionReplayQueue,
    ProjectionReplaySummary,
    ProductProjectionReplayRefusal,
    ProductProjectionTargets,
    RECONSTRUCTABLE_QUEUE_EVENTS,
    RetainedProjectionSource,
    load_durable_projection_work,
    rebuild_product_projections,
)
from .mirror_doctor import (
    DurablePath,
    DurablePathClass,
    MirrorDoctorReport,
    MirrorFinding,
    MirrorFindingCode,
    ProjectionRecord,
    SourceRecord,
    diagnose_mirror_corruption,
)

__all__ = [
    "DbOutboxProjectionQueue",
    "PRODUCT_REPLAY_RECIPE_VERSION",
    "ProductReadiness",
    "ProductReplayRefusal",
    "ProductReplayTuple",
    "canonical_product_body_text",
    "canonical_product_source_text",
    "evaluate_product_store_readiness",
    "parse_bounded_frontmatter",
    "parse_markdown_text",
    "product_replay_provenance",
    "DurableProjectionWork",
    "ProjectionRelation",
    "ProjectionReplayQueue",
    "ProjectionReplaySummary",
    "ProductProjectionReplayRefusal",
    "ProductProjectionTargets",
    "RECONSTRUCTABLE_QUEUE_EVENTS",
    "RetainedProjectionSource",
    "load_durable_projection_work",
    "rebuild_product_projections",
    "DurablePath",
    "DurablePathClass",
    "MirrorDoctorReport",
    "MirrorFinding",
    "MirrorFindingCode",
    "ProjectionRecord",
    "SourceRecord",
    "diagnose_mirror_corruption",
]
