"""Prepare-promotion plan generation.

Produces a deterministic, reviewable promotion plan artifact per the contract
defined in docs/RELEASE_CHANNELS/DEFINE_PROMOTION_PLAN_CONTRACT.md.

Plan generation is side-effect-safe and repeatable: same inputs → same plan shape.
It never moves a ref, applies a migration, or restarts a process.
"""

from __future__ import annotations

import dataclasses
from datetime import date
from pathlib import Path
from typing import Any


class MissingRefError(ValueError):
    """Raised when a required ref (stable_ref or target_ref) is missing or empty."""


@dataclasses.dataclass
class PromotionPlan:
    """The seven required sections of a promotion plan.

    Per docs/RELEASE_CHANNELS/DEFINE_PROMOTION_PLAN_CONTRACT.md.
    """

    # 1. Promotion target: which commits are involved
    promotion_target: dict[str, str]

    # 2. Code delta: ordered PR list (stubs; full enumeration is a follow-up)
    code_delta: list[dict[str, Any]]

    # 3. Migration delta: migrations to apply (stubs; full enumeration is follow-up)
    migration_delta: list[dict[str, Any]]

    # 4. Config / settings delta: operator-visible changes
    config_delta: list[dict[str, Any]]

    # 5. Risk notes: explicit risks for operator review
    risk_notes: list[str]

    # 6. Rollback path: previous stable ref and reversal sequence
    rollback_path: dict[str, Any]

    # 7. Operator acknowledgments: checkboxes for forward-only migrations and AC gaps
    operator_acknowledgments: list[str]

    # Path to the written markdown artifact (set after generate_plan writes it)
    artifact_path: str | None = None


_PLAN_TEMPLATE = """\
# Promotion Plan

Generated by `prepare-promotion`. Review all sections before handing to `execute-promotion`.

---

## Promotion target

- **Stable ref (current prod):** {stable_ref}
- **Target ref (to promote):** {target_ref}
- **Generated:** {generated_date}

---

## Code delta

{code_delta}

---

## Migration delta

{migration_delta}

---

## Config / settings delta

{config_delta}

---

## Risk notes

{risk_notes}

---

## Rollback path

- **Previous stable ref:** {stable_ref}
- **Migration reversal sequence:** See `docs/RELEASE_CHANNELS/DEFINE_ROLLBACK_CONTRACT.md`

---

## Operator acknowledgments

{operator_acknowledgments}

---

*This plan must be reviewed and all acknowledgment checkboxes ticked before `execute-promotion` runs.*
"""


def generate_plan(
    stable_ref: str,
    target_ref: str,
    output_dir: Path | str = Path("ops/promotions"),
) -> PromotionPlan:
    """Generate a promotion plan artifact and write it to output_dir.

    Args:
        stable_ref: The current stable ref (commit SHA or tag) prod is running.
        target_ref: The target ref on main to promote to.
        output_dir: Directory where the markdown artifact is written.
                    Defaults to ops/promotions/.

    Returns:
        PromotionPlan with all seven required sections and artifact_path set.

    Raises:
        MissingRefError: If stable_ref or target_ref is empty.
    """
    _validate_refs(stable_ref, target_ref)

    plan = PromotionPlan(
        promotion_target={
            "stable_ref": stable_ref,
            "target_ref": target_ref,
        },
        code_delta=[],  # Full enumeration: future follow-up
        migration_delta=[],  # Full enumeration: future follow-up
        config_delta=[],  # Full enumeration: future follow-up
        risk_notes=[
            "Code delta enumeration not yet implemented — review manually before execution.",
            "Migration delta enumeration not yet implemented — verify no forward-only migrations exist.",
        ],
        rollback_path={
            "previous_stable_ref": stable_ref,
            "reversal_contract": "docs/RELEASE_CHANNELS/DEFINE_ROLLBACK_CONTRACT.md",
        },
        operator_acknowledgments=[
            "- [ ] I have reviewed the code delta and confirmed all PRs are intended.",
            "- [ ] I have verified no unreviewed forward-only migrations are included.",
            "- [ ] I have run verify-promotion in a dry context.",
            "- [ ] I accept responsibility for promotion of this plan.",
        ],
    )

    artifact_path = _write_artifact(plan, stable_ref, target_ref, Path(output_dir))
    plan.artifact_path = str(artifact_path)
    return plan


def _validate_refs(stable_ref: str, target_ref: str) -> None:
    if not stable_ref or not stable_ref.strip():
        raise MissingRefError("stable_ref must not be empty")
    if not target_ref or not target_ref.strip():
        raise MissingRefError("target_ref must not be empty")


def _write_artifact(
    plan: PromotionPlan,
    stable_ref: str,
    target_ref: str,
    output_dir: Path,
) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)

    short_sha = target_ref[:7]
    filename = f"{date.today().isoformat()}-{short_sha}.md"
    artifact_path = output_dir / filename

    def _bullet_list(items: list[Any], empty_msg: str) -> str:
        if not items:
            return f"_{empty_msg}_"
        return "\n".join(f"- {item}" for item in items)

    content = _PLAN_TEMPLATE.format(
        stable_ref=stable_ref,
        target_ref=target_ref,
        generated_date=date.today().isoformat(),
        code_delta=_bullet_list(plan.code_delta, "No PRs enumerated — review manually."),
        migration_delta=_bullet_list(plan.migration_delta, "No migrations enumerated — verify manually."),
        config_delta=_bullet_list(plan.config_delta, "No config changes enumerated — verify manually."),
        risk_notes=_bullet_list(plan.risk_notes, "No risks identified."),
        operator_acknowledgments="\n".join(plan.operator_acknowledgments),
    )

    artifact_path.write_text(content, encoding="utf-8")
    return artifact_path


__all__ = ["MissingRefError", "PromotionPlan", "generate_plan"]
