"""Provider-free vocabulary for governed archival adapters."""

from app.archival.contracts import (
    AccessAuthority,
    ArchivalAdapter,
    CleanupProof,
    ArtifactClass,
    ArtifactDescriptor,
    ArtifactIdentity,
    DerivationClass,
    DurabilityClass,
    Generation,
    Liveness,
    LivenessState,
    OperationBinding,
    OperationRecord,
    OwnerAuthority,
    OpaqueReference,
    PolicyProfile,
    ProvenanceRef,
    Representation,
    RepresentationRef,
    TransitionStage,
)
from app.archival.transition import (
    ArchivalTransitionKernel,
    DurableFakeAdapter,
    FaultStage,
    TransitionFailure,
    TransitionResult,
)
from app.archival.derived_disposition import (
    DerivativeCandidate,
    DerivativeDisposition,
    DerivativeDispositionDoctor,
    DerivativeDispositionResult,
    DerivativeFinding,
    DerivativeFindingCode,
    OwnerAdmissionRoute,
    RebuildRecipe,
)

__all__ = [
    "AccessAuthority",
    "ArchivalAdapter",
    "CleanupProof",
    "ArtifactClass",
    "ArtifactDescriptor",
    "ArtifactIdentity",
    "DerivationClass",
    "DurabilityClass",
    "Generation",
    "Liveness",
    "LivenessState",
    "OperationBinding",
    "OperationRecord",
    "OwnerAuthority",
    "OpaqueReference",
    "PolicyProfile",
    "ProvenanceRef",
    "Representation",
    "RepresentationRef",
    "TransitionStage",
    "ArchivalTransitionKernel",
    "DurableFakeAdapter",
    "FaultStage",
    "TransitionFailure",
    "TransitionResult",
    "DerivativeCandidate",
    "DerivativeDisposition",
    "DerivativeDispositionDoctor",
    "DerivativeDispositionResult",
    "DerivativeFinding",
    "DerivativeFindingCode",
    "OwnerAdmissionRoute",
    "RebuildRecipe",
]
