"""Provider-free vocabulary for governed archival adapters."""

from app.archival.contracts import (
    AccessAuthority,
    ArchivalAdapter,
    ArtifactClass,
    ArtifactDescriptor,
    ArtifactIdentity,
    DerivationClass,
    DurabilityClass,
    Generation,
    Liveness,
    LivenessState,
    OwnerAuthority,
    OpaqueReference,
    PolicyProfile,
    ProvenanceRef,
    Representation,
    RepresentationRef,
    TransitionStage,
)
from app.archival.transition import (
    ArchivalTransitionKernel,
    DurableFakeAdapter,
    FaultStage,
    TransitionFailure,
    TransitionResult,
)

__all__ = [
    "AccessAuthority",
    "ArchivalAdapter",
    "ArtifactClass",
    "ArtifactDescriptor",
    "ArtifactIdentity",
    "DerivationClass",
    "DurabilityClass",
    "Generation",
    "Liveness",
    "LivenessState",
    "OwnerAuthority",
    "OpaqueReference",
    "PolicyProfile",
    "ProvenanceRef",
    "Representation",
    "RepresentationRef",
    "TransitionStage",
    "ArchivalTransitionKernel",
    "DurableFakeAdapter",
    "FaultStage",
    "TransitionFailure",
    "TransitionResult",
]
